#### Name: Alamin Musa Magaga
#### Email: alaminmusamagaga@gmail.com
#### Title: Week 1 Solution

####  2. Create a random tensor with shape (7, 7).

In [10]:

import torch 

X = torch.rand(size=(7, 7))
X

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [7]:
print(X.shape)

torch.Size([7, 7])

#### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)

In [11]:


Y = torch.rand(size=(1, 7))
# Z = torch.matmul(X, Y)
Z = torch.matmul(X, Y.T) 
Z
     

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [ ]:
print(Z.shape)

#### 4. Set the random seed to 0 and do 2 & 3 over again.

In [13]:
torch.manual_seed(0)

In [15]:

X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z

(tensor([[1.1061],
         [0.9868],
         [1.8999],
         [0.7716],
         [1.3174],
         [1.6353],
         [1.7395]]),
 torch.Size([7, 1]))

In [ ]:
print(Z.shape)

#### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? 

In [16]:

torch.cuda.manual_seed(1234)

#### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed)

In [17]:

torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")


tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
print("tensor_A:",tensor_A)
print("tensor_B:",tensor_B)

Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

#### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors)

In [18]:
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

In [ ]:
print(tensor_C.shape)

#### 8. Find the maximum and minimum values of the output of 7.

In [19]:

# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
print("max:",max)
print("min:",min)

(tensor(0.5617), tensor(0.3647))

#### 9. Find the maximum and minimum index values of the output of 7.

In [20]:
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
print("arg max:",arg_max)
print("arg min:",arg_min)

(tensor(3), tensor(0))

#### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [21]:

torch.manual_seed(7)

tensor_D = torch.rand(size=(1, 1, 1, 10))


tensor_E = tensor_D.squeeze()


print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
