#### Name: Alamin Musa Magaga
#### Email: alaminmusamagaga@gmail.com
#### Title: Week 1 Solution

####  2. Create a random tensor with shape (7, 7).

In [1]:

import torch 

X = torch.rand(size=(7, 7))
X

tensor([[0.2712, 0.5751, 0.2769, 0.8533, 0.4963, 0.3098, 0.4034],
        [0.9143, 0.2440, 0.2227, 0.3161, 0.8505, 0.4585, 0.4540],
        [0.6286, 0.1081, 0.5408, 0.9747, 0.1737, 0.9579, 0.5063],
        [0.6005, 0.7539, 0.5770, 0.8990, 0.6016, 0.7730, 0.6415],
        [0.9483, 0.6938, 0.6381, 0.5699, 0.4376, 0.6192, 0.4418],
        [0.1033, 0.6763, 0.4555, 0.3333, 0.1106, 0.0443, 0.7167],
        [0.5237, 0.7357, 0.1072, 0.2852, 0.9119, 0.2915, 0.2587]])

In [2]:
print(X.shape)

torch.Size([7, 7])


#### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)

In [3]:


Y = torch.rand(size=(1, 7))
# Z = torch.matmul(X, Y)
Z = torch.matmul(X, Y.T) 
Z
     

tensor([[2.1110],
        [2.2387],
        [2.2336],
        [3.0491],
        [2.7042],
        [1.8065],
        [2.0499]])

In [4]:
print(Z.shape)

torch.Size([7, 1])


#### 4. Set the random seed to 0 and do 2 & 3 over again.

In [5]:
torch.manual_seed(0)

In [6]:

X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [7]:
print(Z.shape)

torch.Size([7, 1])


#### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? 

In [8]:

torch.cuda.manual_seed(1234)

#### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed)

In [9]:

torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")


tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
print("tensor_A:",tensor_A)
print("tensor_B:",tensor_B)

Device: cpu
tensor_A: tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor_B: tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


#### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors)

In [10]:
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

In [11]:
print(tensor_C.shape)

torch.Size([2, 2])


#### 8. Find the maximum and minimum values of the output of 7.

In [12]:

# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
print("max:",max)
print("min:",min)

max: tensor(0.5617)
min: tensor(0.3647)


#### 9. Find the maximum and minimum index values of the output of 7.

In [13]:
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
print("arg max:",arg_max)
print("arg min:",arg_min)

arg max: tensor(3)
arg min: tensor(0)


#### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [14]:

torch.manual_seed(7)

tensor_D = torch.rand(size=(1, 1, 1, 10))


tensor_E = tensor_D.squeeze()


print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
